modLoader = "javafml" #mandatory
loaderVersion = "[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "LGPL-3.0" # Review your options at https://choosealicense.com/.
issueTrackerURL="https://github.com/Drullkus/OpenGLDebug/issues" #optional
[[mods]] #mandatory
modId = "opengldebug" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile = "opengldebug.png" #optional (needs to be in the root of your mod jar (root of your 'resources' folder))
#credits = "Thanks for this example mod goes to Java" #optional
authors = "${mod_author}" #optional
description = '''
Automatic annotation for your Minecraft OpenGL frame captures!
''' #mandatory (Supports multiline text)
[[dependencies.opengldebug]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[47,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.opengldebug]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
